import type { AgentAction, IRNode, PageIR, TraceMeta } from "@proa/protocol";
import { findByRef } from "@proa/protocol";
import type { ParsedTrace } from "./parse.js";

const PW_ROLES = new Set([
  "link",
  "button",
  "textbox",
  "searchbox",
  "checkbox",
  "radio",
  "combobox",
  "spinbutton",
  "heading",
  "cell",
  "row",
  "list",
  "listitem",
  "option",
  "img",
]);

function jsStr(s: string): string {
  return JSON.stringify(s);
}

function locatorFor(node: IRNode | undefined): string {
  if (!node) return `page.locator("body")`;
  const name = node.name?.trim();
  if (PW_ROLES.has(node.role)) {
    const opts = name ? `, { name: ${jsStr(name)} }` : "";
    return `page.getByRole(${jsStr(node.role)}${opts})`;
  }
  if (name) return `page.getByText(${jsStr(name)})`;
  return `page.locator("body")`;
}

function lineForAction(action: AgentAction, ir: PageIR | undefined): string[] {
  const p = action.params;
  const node = ir && typeof p.ref === "string" ? findByRef(ir.root, p.ref) : undefined;
  switch (action.tool) {
    case "navigate":
      return [`  await page.goto(${jsStr(String(p.url ?? ""))});`];
    case "tabs.open":
      return p.url ? [`  await page.goto(${jsStr(String(p.url))});`] : [];
    case "click":
      return [`  await ${locatorFor(node)}.click();`];
    case "type": {
      const secret = node?.state?.secret;
      const value = secret
        ? "process.env.PROA_SECRET ?? \"REDACTED\""
        : jsStr(String(p.text ?? ""));
      const lines = [`  await ${locatorFor(node)}.fill(${value});`];
      if (p.submit === true) lines.push(`  await ${locatorFor(node)}.press("Enter");`);
      return lines;
    }
    case "select":
      return [`  await ${locatorFor(node)}.selectOption(${jsStr(String(p.value ?? ""))});`];
    case "waitFor":
      if (p.text) return [`  await page.getByText(${jsStr(String(p.text))}).waitFor();`];
      if (node) return [`  await ${locatorFor(node)}.waitFor();`];
      return [`  await page.waitForTimeout(${Number(p.timeoutMs ?? 500)});`];
    case "scroll":
      return [`  await page.mouse.wheel(0, ${p.direction === "up" ? -600 : 600});`];
    case "screenshot":
      return [`  await page.screenshot({ fullPage: ${p.fullPage === true} });`];
    case "extract":
      return [`  // extract(schema) — verify shape in your assertions (not a Playwright primitive)`];
    case "download":
      return [`  // download gated by the permission engine at runtime`];
    default:
      return [`  // ${action.tool}: no direct Playwright mapping`];
  }
}

export interface ExportOptions {
  testName?: string;
}

/**
 * Export a recorded trace to a runnable Playwright test. Refs are resolved to
 * getByRole locators via the IR snapshot that preceded each action, so the output
 * is stable-selector, human-readable, and runs green against the same site (M4).
 */
export function toPlaywrightTest(trace: ParsedTrace, opts: ExportOptions = {}): string {
  const meta: TraceMeta = trace.meta;
  const name = opts.testName ?? `replay: ${meta.task}`;
  let currentIR: PageIR | undefined;
  const body: string[] = [];
  for (const e of trace.events) {
    if (e.type === "ir.snapshot") currentIR = e.payload as PageIR;
    else if (e.type === "step.action") {
      body.push(...lineForAction(e.payload as AgentAction, currentIR));
    }
  }
  return `import { test, expect } from "@playwright/test";

// Auto-generated by \`proa trace export --as playwright\` from trace ${meta.traceId}.
// Task: ${meta.task}
test(${jsStr(name)}, async ({ page }) => {
${body.join("\n") || "  // (no actions recorded)"}
  await expect(page).toHaveURL(/.*/);
});
`;
}
